# Generated by Django 3.2 on 2022-04-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_student_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='UniversityGroup',
        ),
    ]
