# Generated by Django 3.2 on 2022-05-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_group_universitygroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pickle_dump',
            field=models.FileField(default='', upload_to='tasks/'),
            preserve_default=False,
        ),
    ]
